app:
  name: platform-app
  env: development
  port: 8081

database:
  host: db
  port: 5432
  name: platform-app
  user: postgres
  password: postgres
  max_connections: 100
  timeout: 5s

tracing:
  endpoint: collector:4317
